version: "3.9"
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "$MONGO_HOST_PORT:$MONGO_CONTAINER_PORT"
    volumes:
      - ./mongo.keyfile:/auth/file.key
    command: ["--keyFile", "/auth/file.key", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: test $$(echo "rs.initiate().ok" | mongosh -u $MONGO_USER -p $MONGO_PASSWORD --quiet) -eq 1 || exit 0      
      interval: 5s
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
    depends_on:
      - mongo
    ports:
      - "9999:8081"
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "$POSTGRES_HOST_PORT:$POSTGRES_CONTAINER_PORT"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pagadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@gohexagonalapi.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgres
    ports:
      - "8888:80"
    volumes:
    - ./.pgadmin/servers.json:/pgadmin4/servers.json
  api-mongo:
    image: go-hexagonal-api:$VERSION
    container_name: go-hexagonal-api-mongo-$ENV
    build:
      args:
        version: $VERSION
      context: .
      dockerfile: build/docker/Dockerfile
    environment:
      - env=$ENV
      - p=$CONTAINER_PORT
      - db=mongo
      - dsn=$MONGO_DSN
    depends_on:
      - mongo
    ports:
      - $HOST_PORT_MONGOAPI:$CONTAINER_PORT
  api-postgres:
    image: go-hexagonal-api:$VERSION
    container_name: go-hexagonal-api-postgres-$ENV
    build:
      args:
        version: $VERSION
      context: .
      dockerfile: build/docker/Dockerfile
    environment:
      - env=$ENV
      - p=$CONTAINER_PORT
      - db=postgres
      - dsn=$POSTGRES_DSN
    depends_on:
      - postgres
    ports:
      - $HOST_PORT_POSTGRESAPI:$CONTAINER_PORT