package api

import (
	"context"
	"fmt"
	"log"
	"net"
	"net/http"
	"path/filepath"
	"runtime"

	"github.com/gorilla/mux"
	"github.com/newrelic/go-agent/v3/integrations/nrgorilla"
	"github.com/newrelic/go-agent/v3/newrelic"
	_ "github.com/sergicanet9/go-hexagonal-api/app/docs" // docs is generated by Swag CLI, needs to be imported.
	grpcHandlers "github.com/sergicanet9/go-hexagonal-api/app/grpc/handlers"
	"github.com/sergicanet9/go-hexagonal-api/app/handlers"

	grpcRuntime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/sergicanet9/go-hexagonal-api/config"
	"github.com/sergicanet9/go-hexagonal-api/core/ports"
	"github.com/sergicanet9/go-hexagonal-api/core/services"
	"github.com/sergicanet9/go-hexagonal-api/infrastructure/mongo"
	"github.com/sergicanet9/go-hexagonal-api/infrastructure/postgres"
	pb "github.com/sergicanet9/go-hexagonal-api/proto/protogen"
	"github.com/sergicanet9/scv-go-tools/v3/api/middlewares"
	"github.com/sergicanet9/scv-go-tools/v3/infrastructure"
	"github.com/sergicanet9/scv-go-tools/v3/observability"
	httpSwagger "github.com/swaggo/http-swagger"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/reflection"
)

type api struct {
	config      config.Config
	services    svs
	newrelicApp *newrelic.Application
}

type svs struct {
	user ports.UserService
}

// New creates a new API
func New(ctx context.Context, cfg config.Config, nrApp *newrelic.Application) (a api) {
	a.config = cfg
	a.newrelicApp = nrApp

	var userRepo ports.UserRepository
	switch a.config.Database {
	case "mongo":
		db, err := infrastructure.ConnectMongoDB(ctx, a.config.DSN)
		if err != nil {
			observability.Logger().Fatal(err)
		}

		userRepo, err = mongo.NewUserRepository(ctx, db)
		if err != nil {
			observability.Logger().Fatal(err)
		}
	case "postgres":
		db, err := infrastructure.ConnectPostgresDB(ctx, a.config.DSN)
		if err != nil {
			observability.Logger().Fatal(err)
		}

		_, filePath, _, _ := runtime.Caller(0)
		migrationsDir := filepath.Join(filePath, "../../..", cfg.PostgresMigrationsDir)
		err = infrastructure.MigratePostgresDB(db, migrationsDir)
		if err != nil {
			observability.Logger().Fatal(err)
		}

		userRepo = postgres.NewUserRepository(db)
	default:
		observability.Logger().Fatalf("database flag %s not valid", a.config.Database)
	}

	a.services.user = services.NewUserService(a.config, userRepo)
	return a
}

// Run API
func (a *api) Run(ctx context.Context, cancel context.CancelFunc) func() error {
	return func() error {
		defer cancel()

		router := mux.NewRouter()
		router.Use(middlewares.Recover)
		router.Use(nrgorilla.Middleware(a.newrelicApp))

		healthHandler := handlers.NewHealthHandler(ctx, a.config)
		handlers.SetHealthRoutes(router, healthHandler)

		userHandler := handlers.NewUserHandler(ctx, a.config, a.services.user)
		handlers.SetUserRoutes(router, userHandler)

		router.PathPrefix("/swagger").HandlerFunc(httpSwagger.WrapHandler)

		observability.Logger().Printf("Version: %s", a.config.Version)
		observability.Logger().Printf("Environment: %s", a.config.Environment)
		observability.Logger().Printf("Database: %s", a.config.Database)
		observability.Logger().Printf("Listening on port %d", a.config.Port)

		server := &http.Server{
			Addr:    fmt.Sprintf(":%d", a.config.Port),
			Handler: router,
		}
		go shutdown(ctx, server)
		return server.ListenAndServe()
	}
}

func shutdown(ctx context.Context, server *http.Server) {
	<-ctx.Done()
	observability.Logger().Printf("Shutting down API gracefully...")
	server.Shutdown(ctx)
}

func (a *api) RunGRPC(ctx context.Context, cancel context.CancelFunc) func() error {
	return func() error {
		defer cancel()

		grpcPort := 50051 //TODO: send arg
		lis, err := net.Listen("tcp", fmt.Sprintf(":%d", grpcPort))
		if err != nil {
			log.Fatalf("failed to listen on gRPC port: %v", err)
		}

		server := grpc.NewServer()
		healthHander := grpcHandlers.NewHealthHandler(ctx, a.config)
		pb.RegisterHealthServiceServer(server, healthHander)

		reflection.Register(server)

		go shutdownGRPC(ctx, server)
		observability.Logger().Printf("Listening on gRPC port %d", grpcPort)
		return server.Serve(lis)
	}
}

func shutdownGRPC(ctx context.Context, server *grpc.Server) {
	<-ctx.Done()
	observability.Logger().Printf("Shutting down GRPC API gracefully...")
	server.GracefulStop()
}

func (a *api) RunGRPCGateway(ctx context.Context, cancel context.CancelFunc) func() error {
	return func() error {
		defer cancel()
		httpPort := a.config.Port
		grpcServerEndpoint := fmt.Sprintf("localhost:%d", 50051) //TODO: send arg

		mux := grpcRuntime.NewServeMux()
		opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())}

		err := pb.RegisterHealthServiceHandlerFromEndpoint(ctx, mux, grpcServerEndpoint, opts)
		if err != nil {
			observability.Logger().Fatalf("failed to register gateway: %v", err)
		}

		observability.Logger().Printf("Starting gRPC-Gateway server on port %d, proxying to %s", httpPort, grpcServerEndpoint)
		return http.ListenAndServe(fmt.Sprintf(":%d", httpPort), mux)
	}
}
