name: CD

on:
  push:
    tags:
       - '*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set version tag
      id: vars
      run: echo "tag=$(echo ${{ github.ref_name }} | xargs basename)" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      run: |
        docker build -f build/docker/Dockerfile --build-arg version=${{ steps.vars.outputs.tag }} -t ghcr.io/${{ github.repository }}/go-hexagonal-api:${{ steps.vars.outputs.tag }} .
        docker push ghcr.io/${{ github.repository }}/go-hexagonal-api:${{ steps.vars.outputs.tag }}

  mongo-prod:
    needs: build-and-push
    uses: ./.github/workflows/deployment.yml
    with:
      GITHUB_CONTAINERREGISTRY_URL: ghcr.io
      GCP_CLUSTER_REGION: us-central1
      GCP_CLUSTER_NAME: my-gke-cluster
      ENVIRONMENT: prod
      PORT: 80
      NODEPORT: 30001
      DATABASE: mongo
      VERSION: ${{ needs.build-and-push.outputs.tag }}
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      DSN: ${{ secrets.MONGO_DSN }}
