name: deployment-cloudflared
on:
  workflow_call:
    inputs:
      GCP_CLUSTER_REGION:
        required: true
        type: string
      GCP_CLUSTER_NAME:
        required: true
        type: string

    secrets:
      GCP_PROJECT_ID:
        required: true
      GCP_SA_KEY:
        required: true
      NRIA_LICENSE_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ inputs.GCP_CLUSTER_NAME }}
          location: ${{ inputs.GCP_CLUSTER_REGION }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Create newrelic secrets
        run: |
          kubectl create secret generic nri-bundle-newrelic-infrastructure-license \
          --from-literal=licenseKey="${{ secrets.NRIA_LICENSE_KEY }}" \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to GKE
        run: |
          kubectl apply -f build/k8s/manifest-newrelic.yml
