name: deployment-api
on:
  workflow_call:
    inputs:
      GITHUB_CONTAINERREGISTRY_URL:
        required: true
        type: string
      GCP_CLUSTER_REGION:
        required: true
        type: string
      GCP_CLUSTER_NAME:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      HTTP_PORT:
        required: true
        type: number
      GRPC_PORT:
        required: true
        type: number
      DATABASE:
        required: true
        type: string
      VERSION:
        required: true
        type: string
    secrets:
      GCP_PROJECT_ID:
        required: true
      GCP_SA_KEY:
        required: true
      DSN:
        required: true
      NEWRELIC_KEY:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.GITHUB_CONTAINERREGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ inputs.GCP_CLUSTER_NAME }}
          location: ${{ inputs.GCP_CLUSTER_REGION }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Replace params and environment data in manifest-api file
        run: |
          sed -i "s|__ghcr__|${{ inputs.GITHUB_CONTAINERREGISTRY_URL }}/${{ github.repository }}|g" build/k8s/manifest-api.yml
          sed -i "s|__version__|${{ inputs.VERSION }}|g" build/k8s/manifest-api.yml
          sed -i "s|__environment__|${{ inputs.ENVIRONMENT }}|g" build/k8s/manifest-api.yml
          sed -i "s|__httpport__|${{ inputs.HTTP_PORT }}|g" build/k8s/manifest-api.yml
          sed -i "s|__grpcport__|${{ inputs.GRPC_PORT }}|g" build/k8s/manifest-api.yml
          sed -i "s|__database__|${{ inputs.DATABASE }}|g" build/k8s/manifest-api.yml
          sed -i "s|__nrkey__|${{ secrets.NEWRELIC_KEY }}|g" build/k8s/manifest-api.yml

          ESCAPED_DSN=$(echo "${{ secrets.DSN }}" | sed 's/[&/|]/\\&/g')
          sed -i "s|__dsn__|$ESCAPED_DSN|g" build/k8s/manifest-api.yml

      - name: Deploy to GKE
        run: |
          kubectl apply -f build/k8s/manifest-api.yml
          kubectl rollout restart deployment go-hexagonal-api-${{ inputs.DATABASE }}-${{ inputs.ENVIRONMENT }}
          kubectl rollout status deployment go-hexagonal-api-${{ inputs.DATABASE }}-${{ inputs.ENVIRONMENT }}
